name: Force Gradle 8.2 & Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # تثبيت Gradle مؤقتًا لتوليد الـwrapper
      - name: Install Gradle
        run: sudo apt-get update && sudo apt-get install -y gradle

      # إنشاء أو تعديل ملف gradle-wrapper.properties لنسخة 8.2
      - name: Force Gradle 8.2 in wrapper
        run: |
          mkdir -p gradle/wrapper
          echo "distributionUrl=https\\://services.gradle.org/distributions/gradle-8.2-all.zip" > gradle/wrapper/gradle-wrapper.properties
          gradle wrapper --gradle-version 8.2 --distribution-type all
          chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: font-apk
          path: app/build/outputs/apk/debug/*.apk
